export enum JobOrderStatus {
  PENDING_ASSIGNMENT = 'PENDING_ASSIGNMENT',
  ASSIGNED = 'ASSIGNED',
  DRIVER_ACCEPTED = 'DRIVER_ACCEPTED',
  IN_PROGRESS = 'IN_PROGRESS',
  DELIVERED = 'DELIVERED',
  POD_SUBMITTED = 'POD_SUBMITTED',
  COMPLETED = 'COMPLETED',
  CANCELLED = 'CANCELLED'
}
