/**
 * Sentralogis — U-09 Fabricated-ID Elimination: Forensic Tests
 *
 * Validates that no client-side code fabricates canonical domain identifiers.
 * Client may express business intent; it must never manufacture the identity
 * of a persistent canonical logistics aggregate.
 */

import { ShipmentFactory } from '../shipment-factory';
import { ExecutionPlanService } from '../execution-plan-service';
import { CreateShipmentDTO, CreateExecutionLegDTO } from '../types';
import * as fs from 'fs';
import * as path from 'path';

export function runFabricatedIdEliminationSuite() {
  const results: Array<{ testId: string; description: string; pass: boolean; error?: string }> = [];

  function assert(testId: string, description: string, fn: () => void) {
    try {
      fn();
      results.push({ testId, description, pass: true });
    } catch (e: any) {
      results.push({ testId, description, pass: false, error: e.message || String(e) });
    }
  }

  function readFile(relPath: string): string {
    const full = path.resolve(process.cwd(), relPath);
    return fs.readFileSync(full, 'utf-8');
  }

  // =========================================================================
  // F1 — No fabricated shipment ID
  // =========================================================================
  assert('F1', 'Shipment creation DTO accepts optional work_order_id (no client fabrication required)', () => {
    const dto: CreateShipmentDTO = {
      tenant_id: 'ten-01',
      customer_id: 'cus-01',
      origin_location_id: 'CNSHA',
      destination_location_id: 'IDBYD',
    };
    if (dto.work_order_id !== undefined) {
      throw new Error('work_order_id should be undefined when not provided by client');
    }
  });

  // =========================================================================
  // F2 — No fabricated execution-leg ID
  // =========================================================================
  assert('F2', 'ExecutionPlanService generates legs with server-side IDs (not client-fabricated)', () => {
    const svc = new ExecutionPlanService();
    const legs: CreateExecutionLegDTO[] = [
      { leg_sequence: 1, leg_code: 'L1', transport_mode: 'OCEAN_VESSEL', origin_location_id: 'CNSHA', destination_location_id: 'IDPTB' },
    ];
    const { plan, legs: built } = svc.buildPlanAndLegs('shp-01', 'ten-01', legs);
    if (!plan.id || plan.id.length === 0) throw new Error('Plan ID must be generated server-side');
    if (!built[0].id || built[0].id.length === 0) throw new Error('Leg ID must be generated server-side');
  });

  // =========================================================================
  // F3 — No fabricated shipment-unit ID
  // =========================================================================
  assert('F3', 'ShipmentFactory generates unit IDs server-side when creating entities', () => {
    const units = ShipmentFactory.createUnitEntities('shp-01', 'ten-01', [
      {
        unit_type: 'CONTAINER',
        unit_identifier: 'MSKU1234567',
        container_number: 'MSKU1234567',
        iso_type: '40HC',
        total_gross_weight_kg: 28000,
      },
    ]);
    if (!units[0].id || units[0].id.length === 0) {
      throw new Error('Unit ID must be generated by factory/server-side');
    }
  });

  // =========================================================================
  // F4 — Engagement authority
  // =========================================================================
  assert('F4', 'Shipment DTO accepts omission of work_order_id — server resolves via U-03', () => {
    const dto: CreateShipmentDTO = {
      tenant_id: 'ten-01',
      customer_id: 'cus-real-01',
      origin_location_id: 'CNSHA',
      destination_location_id: 'IDBYD',
    };
    const shp = ShipmentFactory.createShipmentEntity(dto);
    if (shp.work_order_id !== '') {
      throw new Error('When work_order_id is omitted, factory should use empty string placeholder');
    }
  });

  // =========================================================================
  // F5 — Tenant authority
  // =========================================================================
  assert('F5', 'Shipment API route overrides client tenant_id with auth.tenantId (never trusts client)', () => {
    const routeSrc = readFile('app/api/v1/forwarding/shipments/route.ts');
    if (!routeSrc.includes('tenant_id: auth.tenantId')) {
      throw new Error('Route must override tenant_id with auth.tenantId');
    }
  });

  // =========================================================================
  // F6 — Persistence integrity
  // =========================================================================
  assert('F6', 'Created shipment references authoritative IDs from factory/server', () => {
    const dto: CreateShipmentDTO = {
      tenant_id: 'ten-01',
      work_order_id: 'wo-comm-001',
      service_scope_id: 'scope-01',
      customer_id: 'cus-01',
      origin_location_id: 'CNSHA',
      destination_location_id: 'IDBYD',
    };
    const shp = ShipmentFactory.createShipmentEntity(dto);
    if (!shp.id) throw new Error('Shipment must have a generated ID');
    if (!shp.tracking_token) throw new Error('Shipment must have a tracking token');
    if (!shp.shipment_number.startsWith('SHP-')) throw new Error('Shipment number must follow SHP-YYYYMM-XXXXXX format');
  });

  // =========================================================================
  // F7 — Repeated creation behavior
  // =========================================================================
  assert('F7', 'Factory generates unique shipment IDs on each creation (no collision)', () => {
    const dto: CreateShipmentDTO = {
      tenant_id: 'ten-01',
      work_order_id: 'wo-01',
      service_scope_id: 'scope-01',
      customer_id: 'cus-01',
      origin_location_id: 'CNSHA',
      destination_location_id: 'IDBYD',
    };
    const shp1 = ShipmentFactory.createShipmentEntity(dto);
    const shp2 = ShipmentFactory.createShipmentEntity(dto);
    if (shp1.id === shp2.id) {
      throw new Error('Consecutive shipments must have unique IDs');
    }
    if (shp1.shipment_number === shp2.shipment_number) {
      throw new Error('Consecutive shipments must have unique shipment numbers');
    }
  });

  // =========================================================================
  // F8 — Existing contract preservation
  // =========================================================================
  assert('F8', 'ShipmentAggregate structure preserved (shipment, manifest_items, units, legs, etc.)', () => {
    const dto: CreateShipmentDTO = {
      tenant_id: 'ten-01',
      work_order_id: 'wo-01',
      service_scope_id: 'scope-01',
      customer_id: 'cus-01',
      origin_location_id: 'CNSHA',
      destination_location_id: 'IDBYD',
    };
    const shp = ShipmentFactory.createShipmentEntity(dto);
    const requiredFields = ['id', 'tenant_id', 'shipment_number', 'work_order_id', 'service_scope_id', 'customer_id',
      'origin_location_id', 'destination_location_id', 'global_status', 'tracking_token', 'version_no', 'created_at', 'updated_at'];
    for (const field of requiredFields) {
      if ((shp as any)[field] === undefined) {
        throw new Error(`Shipment entity missing required field: ${field}`);
      }
    }
    if (shp.global_status !== 'DRAFT') throw new Error('New shipment must be in DRAFT status');
  });

  // =========================================================================
  // F9 — Static proof: no forbidden canonical-ID fabrication in client code
  // =========================================================================
  assert('F9', 'Client page.tsx contains no crypto.randomUUID() for work_order_id or service_scope_id', () => {
    const pageSrc = readFile('app/(dashboard)/sbu/forwarding/shipments/create/page.tsx');
    if (pageSrc.includes('work_order_id:') && pageSrc.includes('randomUUID')) {
      throw new Error('page.tsx still fabricates work_order_id with crypto.randomUUID()');
    }
    if (pageSrc.includes('service_scope_id:') && pageSrc.includes('randomUUID')) {
      throw new Error('page.tsx still fabricates service_scope_id with crypto.randomUUID()');
    }
  });

  assert('F9b', 'Client page.tsx contains no cus_${Date.now()} fallback for customer_id', () => {
    const pageSrc = readFile('app/(dashboard)/sbu/forwarding/shipments/create/page.tsx');
    if (pageSrc.includes('cus_${Date.now()}')) {
      throw new Error('page.tsx still fabricates customer_id with Date.now() fallback');
    }
  });

  assert('F9c', 'ShipmentIdentityForm.tsx contains no customer_id slug fabrication from name', () => {
    const formSrc = readFile('components/workspaces/forwarding/ShipmentCreator/ShipmentIdentityForm.tsx');
    if (formSrc.includes('cus_${') || formSrc.includes("customer_id', `cus_")) {
      throw new Error('ShipmentIdentityForm.tsx still fabricates customer_id from name slug');
    }
  });

  assert('F9d', 'CargoComposer.tsx contains no Math.random() for canonical unit identifiers', () => {
    const composerSrc = readFile('components/workspaces/forwarding/ShipmentCreator/CargoComposer.tsx');
    if (composerSrc.includes('Math.random()') && composerSrc.includes('unit_identifier')) {
      throw new Error('CargoComposer.tsx still uses Math.random() for unit_identifier fallback');
    }
    if (composerSrc.includes('Date.now()') && composerSrc.includes('unit_identifier')) {
      throw new Error('CargoComposer.tsx still uses Date.now() for unit_identifier fallback');
    }
  });

  assert('F9e', 'Shipment API route resolves engagement via U-03 when work_order_id missing', () => {
    const routeSrc = readFile('app/api/v1/forwarding/shipments/route.ts');
    if (!routeSrc.includes('resolveOrCreateEngagement')) {
      throw new Error('API route must use U-03 resolveOrCreateEngagement for missing work_order_id');
    }
    if (!routeSrc.includes('tenant_id: auth.tenantId')) {
      throw new Error('API route must override tenant_id with auth.tenantId');
    }
  });

  // =========================================================================
  // F10 — Scope containment: no U-07/U-08 regression
  // =========================================================================
  assert('F10a', 'U-08 forwarding-writer.ts is untouched (still uses canonical engagement)', () => {
    const writerSrc = readFile('lib/application/service-contracts/forwarding-writer.ts');
    if (!writerSrc.includes('resolveOrCreateEngagement')) {
      throw new Error('U-08 forwarding-writer must still use U-03 resolveOrCreateEngagement');
    }
  });

  assert('F10b', 'U-07 execution-plan-service.ts is untouched (generates IDs server-side)', () => {
    const epsSrc = readFile('lib/domain/shipment/execution-plan-service.ts');
    if (!epsSrc.includes('crypto.randomUUID')) {
      throw new Error('U-07 execution-plan-service must still generate IDs server-side');
    }
  });

  assert('F10c', 'No direct browser-side .from(...).insert(...) in forwarding shipment creation UI', () => {
    const pageSrc = readFile('app/(dashboard)/sbu/forwarding/shipments/create/page.tsx');
    if (pageSrc.includes('.from(') && pageSrc.includes('.insert(')) {
      throw new Error('Client page.tsx contains direct Supabase insert — violation of authority boundary');
    }
  });

  return results;
}
