REVOKE EXECUTE ON FUNCTION public.create_driver(UUID, UUID, TEXT, TEXT, TEXT, TEXT, TEXT, TEXT, TEXT, TEXT, BOOLEAN, TEXT) FROM anon;
REVOKE EXECUTE ON FUNCTION public.update_driver(UUID, UUID, TEXT, TEXT, BOOLEAN, TEXT, TEXT, TEXT, TEXT, TEXT, UUID) FROM anon;
REVOKE EXECUTE ON FUNCTION public.deactivate_driver(UUID, UUID) FROM anon;
REVOKE EXECUTE ON FUNCTION public.merge_driver_profile(UUID, UUID) FROM anon;
REVOKE EXECUTE ON FUNCTION public.has_tenant_access(UUID) FROM anon;
REVOKE EXECUTE ON FUNCTION public.is_superadmin() FROM anon;
